
title = "Vishus Blog"

# The URL the site will be built for
base_url = "https://vishusandy.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false
# highlight_theme = "inspired-github"

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether external links are to be opened in a new tab
# If this is true, a `rel="noopener"` will always automatically be added for security reasons
external_links_target_blank = true

# Whether to set rel="nofollow" for all external links
external_links_no_follow = true

# Whether to set rel="noreferrer" for all external links
external_links_no_referrer = true

[extra]
katex_enable = true
katex_auto_render = true

[[extra.links]]
text = "Links"
url = "/pages/links"

[[extra.links]]
text = "<i class=\"link-icon fa-brands fa-github\" alt=\"My GitHub profile\" title=\"My GitGub\"></i>"
url = "https://github.com/vishusandy"
static_url = true
new_window = true

[[extra.links]]
text = "<i class=\"link-icon fa-brands fa-mastodon\"></i>"
url = "https://social.linux.pizza/@vishus"
static_url = true
attribues = "rel=\"me\" target=\"_blank\""
