


name: Zola GitHub pages
on:
  push:
    branches:
      - main

jobs:
  zola:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Zola
        run: curl -L ${BASE_URL}/${VERS}/zola-${VERS}-${ARCH}.tar.gz | tar -xz
      - name: Zola Build
        run: ./zola build
      - name: Deploy Zola
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: gh-pages
          build_dir: public
    env:
      BASE_URL: https://github.com/getzola/zola/releases/download
      VERS: v0.16.1
      ARCH: x86_64-unknown-linux-gnu
      # https://github.com/crazy-max/ghaction-github-pages/issues/1#issuecomment-623202206
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





# name: Zola on GitHub Pages

# on: 
#  push:
#   branches:
#    - main

# jobs:
#   build:
#     name: Publish site
#     runs-on: ubuntu-latest
#     steps:
#     - name: Checkout main
#       uses: actions/checkout@v3.0.0
#     - name: Build and deploy
#       uses: shalzz/zola-deploy-action@v0.16.1
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         # Target branch
#         PAGES_BRANCH: gh-pages
#         # Provide personal access token
#         # Or if publishing to the same repo, use the automatic token
#         #TOKEN: ${{ secrets.GITHUB_TOKEN }}
#         BUILD_DIR: zola/blog
#         OUT_DIR: docs
#         # BUILD_ONLY: true
